spring.application.name=FuelSalesPaymentReporting
spring.application.name=FuelSalesPaymentReporting

spring.datasource.url=jdbc:mysql://localhost:3306/vsfms_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=tharusha19651

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.thymeleaf.cache=false